apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-deployment
spec:
  selector:
    matchLabels:
      app: servicio
  replicas: 3
  template:
    metadata:
      labels:
        app: servicio
    spec:
      containers:
      - name: servicio-contenedor
        image: acrmicroservicio952024.azurecr.io/microservicio-devops:latest
        ports:
        - containerPort: 3000